config/routes.rb
Dddeals::Application.routes.draw do
  devise_for :members#,:controllers => { :registrations =>'registration'}

	get 'deals/mine', to: 'deals#mine', as: "mydeals"
        get 'deals/search', to: 'deals#search', as: "searchdeals"
        post 'deals/searchdealsresult', to: 'deals#searchdealsresult', as:"searchdealsresult"
 
  resources :deals do
  end

   root :to => 'home#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(member)
#    member ||= Member.new
    can :read, :deal

#    if member.has_role? :guest
#      can :read, Member
#    end
#    current_user = current_member
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/deal.rb
class Deal < ActiveRecord::Base
  belongs_to :member
  attr_accessible :actualprice, :address, :contact, :discountprice, :enddate, :location, :startdate, :dealtype, :dealname

  validates :actualprice, :address, :contact, :discountprice, :enddate, :location, :startdate, :dealtype, :dealname, :presence => true
  validates :discountprice, :numericality => {:less_than_or_equal_to => :actualprice} 
  validates :location, length: { maximum: 20}
  validates :contact, length: {minimum:10, maximum: 15}
  validates :actualprice, length:{maximum:10}
#  validate  :date_not_proper
  validate  :end_greater_than_start
  validates_numericality_of :contact, :discountprice, :actualprice

def end_greater_than_start
 if startdate.nil? 
  errors.add(:startdate, "Not in proper format")
 end
 
 if enddate.nil?
  errors.add(:enddate,"Not in proper format")
  return
 end 

 if startdate < Date.today 
  errors.add(:startdate,"Should be greater than today's date")
  return
 end
 
 if startdate > enddate
  errors.add(:startdate,"cannot be greater than enddate")
 end
end 

def date_not_proper
 if startdate == nil
   errors.add(:startdate,"Date not given in proper format")
 end 
 if enddate == nil
   errors.add(:enddate,"Date not given in proper format")
 end
end

end

app/models/member.rb
class Member < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  has_many :deals
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
#  before_filter :authenticate_member! 
  def current_ability
   @current_ability ||=Ability.new(current_member)
  end 
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController

#load_and_authorize_resource

def index
@deals = Deal.all
#@val = member_signed_in?
end

def show
@deal = Deal.find(params[:id])
end

def edit
if member_signed_in? 
 @deal = Deal.find(params[:id])
 if  @deal.member_id != current_member.id
  flash.alert = "You are not authorized to edit this deal"
  redirect_to root_path
 end
else
 flash.notice = "Please login to make changes to the deal"
 redirect_to root_path
#authorized! if can? :edit, @deal
end
end

def update
 @deal = Deal.find(params[:id])
 
  if @deal.update_attributes(params[:deal])
   redirect_to mydeals_path
  else
    render 'edit'
  end
end

def new
 if member_signed_in?
  @deal = Deal.new
 else
  flash.notice = "Please login to create Deals" 
  redirect_to root_path
 end
 @deal = Deal.new
end

def destroy
 @deal = Deal.find(params[:id])
 @deal.destroy
 
 redirect_to mydeals_path
end

def create
 @deal = Deal.new(params[:deal])
 @deal.member_id = current_member.id
 if  @deal.save
  redirect_to mydeals_path
 else
  render 'new'
 end
end

def searchdealsresult
 @dt= params[:dealssearchparam][:date]
 @typ = params[:dealssearchparam][:dealtype]
 @loc = params[:dealssearchparam][:location]

 if @dt.blank? or @typ.blank? or @loc.blank?
  flash.alert ='Please specify the date,type and location'
  render 'search'
  return
 end

 @gh=Date.parse @dt
 @deals =Deal.where("(date(startdate) <= date(?)  AND date(enddate) >=date(?)) AND dealtype = ? AND location = ?",@gh,@gh,@typ,@loc)
end

def mine
	#raise "Unknown" 
if member_signed_in?
 @deals = Deal.where(:member_id => current_member.id)
else
 redirect_to root_path
end
#@deal =  Deal.where(:member_id => current_member.id)
 #render 'deals/mine' 
	#render :action => "mine"
end

def search
end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController

def index
# Deal.destroy_all()
 @deals = Deal.find(:all,:order => 'actualprice-discountprice desc', :limit => 5)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/views/deals/create.html.erb
<p>
<%= @deal.startdate %>
<%= @deal.enddate %>
<%= @deal.location %>
<%= @deal.actualprice %>
<%= @deal.discountprice %>
<%= @deal.address %>
<%= @deal.contact %>
<%= @deal.dealtype %>
<%= @deal.member_id %>
</p>

app/views/deals/edit.html.erb
<h1>Editing Deals</h1>
 
<%= form_for :deal, url: deal_path(@deal), method: :put do |f| %>
  <% if @deal.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@deal.errors.count, "error") %> prohibited
      this article from being saved:</h2>
    <ul>
    <% @deal.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <p>
    <%= f.label :DealName %><br>
    <%= f.text_field :dealname %>
  </p>

  <p>
    <%= f.label :Startdate %><br>
    <%= f.text_field :startdate, :id => "datepicker" %>
  </p>

  <p>
    <%= f.label :Enddate %><br>
    <%= f.text_field :enddate, :id => "datepicker1" %>
  </p>

  <p>
     <%= f.label :Type %>
     <%= f.select :dealtype, options_for_select(%w[Resort PaintBall Rafting Bowling]) %>
 </p>

  <p>
    <%= f.label :Location %><br>
    <%= f.text_field :location %>
  </p>

  <p>
    <%= f.label :ActualPrice %><br>
    <%= f.text_field :actualprice %>
  </p>

  <p>
    <%= f.label :DiscountPrice %><br>
    <%= f.text_field :discountprice %>
  </p>

  <p>
    <%= f.label :ContactNumber %><br>
    <%= f.text_field :contact %>
  </p>

  <p>
    <%= f.label :Address %><br>
    <%= f.text_area :address %>
  </p>

  <p>
    <%= f.submit 'Update Deal' %>
  </p>
                                                                                                                                                                                 
<% end %>
 

app/views/deals/index.html.erb
 <h1>All Deals</h1>

<% if @deals.length == 0%>
   <p> No Deals created so far</p>
<% else %>


<ol class ="deals">

 <% @deals.each do |deal| %>
  <li>
    <span class="content">
    <%=link_to deal.dealname, deal_path(deal) %><br>
    Location: <%= deal.location %><br>
    DealType: <%= deal.dealtype %><br>
    Price: <%= deal.actualprice %><br>
    DiscountPrice: <%= deal.discountprice %><br>
    </span>
  </li>
 <% end %>
</ol>
<% end %>

app/views/deals/mine.html.erb
 <h1>Your Deals</h1>

<% if @deals.length == 0%>
   <p> No Deals created so far</p>
<% else %>


<ol class ="deals">

 <% @deals.each do |deal| %>
  <li>
    <span class="content">
    <%=link_to deal.dealname, deal_path(deal) %><br>
    Location: <%= deal.location %><br>
    DealType: <%= deal.dealtype %><br>
    <%= link_to '<button>Edit</button>'.html_safe, edit_deal_path(deal), :class=>"inbox-sf-add-btn tip" %>
    <%= link_to '<button>Delete</button>'.html_safe, deal_path(deal),
                    method: :delete, data: { confirm: 'Are you sure?' } %>

    </span>
  </li>
 <% end %>
</ol>
<% end %>

app/views/deals/new.html.erb
<%= form_for :deal,url: deals_path do |f| %>

<% if @deal.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@deal.errors.count, "error") %> prohibited
      this article from being saved:</h2>
    <ul>
    <% @deal.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <p>
    <%= f.label :DealName %><br>
    <%= f.text_field :dealname %>
  </p>

  <p>
    <%= f.label :Startdate %><br>
    <%= f.text_field :startdate, :id => "datepicker" %>
  </p>

  <p>
    <%= f.label :Enddate %><br>
    <%= f.text_field :enddate, :id => "datepicker1" %>
  </p>

  <p>
     <%= f.label :Type %> 
     <%= f.select :dealtype, options_for_select(%w[Resort PaintBall Rafting Bowling]) %> 
 </p>

  <p>
    <%= f.label :Location %><br>
    <%= f.text_field :location %>
  </p>

  <p>
    <%= f.label :ActualPrice %><br>
    <%= f.text_field :actualprice %>
  </p>

  <p>
    <%= f.label :DiscountPrice %><br>
    <%= f.text_field :discountprice %>
  </p>

  <p>
    <%= f.label :ContactNumber %><br>
    <%= f.text_field :contact %>
  </p>

  <p>
    <%= f.label :Address %><br>
    <%= f.text_area :address %>
  </p>

  <p>
    <%= f.submit 'Create Deal' %>
  </p>
<% end %>

app/views/deals/search.html.erb
<%= form_for :dealssearchparam,url: searchdealsresult_path do |f| %>
  <p>
    <%= f.label :date %><br>
    <%= f.text_field :date, :id => "datepicker2" %>
  </p>

  <p>
     <%= f.label :Type %>
     <%= f.select :dealtype, options_for_select(%w[Resort PaintBall Rafting Bowling]) %>
 </p>

  <p>
    <%= f.label :Location %><br>
    <%= f.text_field :location %>
  </p>

  <p>
   <%= f.submit 'Search Deals' %>
  </p>
<% end %>

app/views/deals/searchdealsresult.html.erb
 <h1>Result Deals</h1>

<% if @deals.length == 0%>
   <p> No Deals with your requirements found</p>
<% else %>


<ol class ="deals">

 <% @deals.each do |deal| %>
  <li>
    <span class="content">
    <%=link_to deal.dealname, deal_path(deal) %><br>
    Location: <%= deal.location %><br>
    DealType: <%= deal.dealtype %><br>
    Price: <%= deal.actualprice %><br>
    DiscountPrice: <%= deal.discountprice %><br>
    </span>
  </li>
 <% end %>
</ol>
<% end %>

app/views/deals/show.html.erb
<p>
 <strong>DealName: </strong> <%= @deal.dealname %>
</p>

<p>
 <strong>StartDate: </strong> <%= @deal.startdate %>
</p>

<p>
  <strong>EndDate: </strong><%= @deal.enddate %>
</p>

<p>
  <strong>Location: </strong><%= @deal.location %>
</p>

<p>
  <strong>DealType: </strong><%= @deal.dealtype %> 
</p>

<p>
  <strong>ActualPrice: </strong><%= @deal.actualprice %> 
</p>

<p>
  <strong>DiscountPrice: </strong><%= @deal.discountprice %> 
</p>

<p>
  <strong>Contact: </strong><%= @deal.contact %> 
</p>

<p>
  <strong>Address: </strong><%= @deal.address %> 
</p>

app/views/home/index.html.erb
<div class="center hero-unit">
  <h1>Chronus Deals</h1>
</div>
 <h2> Top Deals </h2>
<% if @deals.length == 0%>
   <p> No Deals available</p>
<% else %>


<ol class ="deals">

 <% @deals.each do |deal| %>
  <li> 
    <span class="content">
    <%=link_to deal.dealname, deal_path(deal) %><br>
    Location: <%= deal.location %><br>
    DealType: <%= deal.dealtype %><br>
    Price: <%= deal.actualprice %><br>
    DiscountPrice: <%= deal.discountprice %><br>
    </span>
  </li>
 <% end %>
</ol>
<% end %>

app/views/layouts/_header.html.erb
 <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <nav>
            <ul class="nav pull-right">
              <li class="active">   <%= link_to 'Home' , root_path%> </li>
              <li class="active"><a href="/deals">View All Deals</a></li>
              <li class="active"><a href="/deals/search">Search Deals</a></li>
              <% if member_signed_in? %>
              <li>   <%= link_to 'Edit profile', edit_member_registration_path %> </li>
              <li>   <%= link_to 'My Deals', mydeals_path %> </li>
              <li>   <%= link_to 'New Deal',new_deal_path %> </li>
              <li>   <%= link_to current_member.email, root_path %> </li>
              <li>   <%= link_to "Logout", destroy_member_session_path, method: :delete %> </li>
             <% else %>
              <li>  <%= link_to "Sign up", new_member_registration_path  %> </li>
              <li>  <%= link_to "Login", new_member_session_path  %> </li>
             <% end %>
            </ul>
          </nav>
        </div>
      </div>
 </header>
   

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

 <title>Deals</title>
  <%= javascript_include_tag "jquery-ui-1.10.4.custom" %>
  <%= stylesheet_link_tag    "application", :media => "all","data-turbolinks-track" => true %>
  <%= javascript_include_tag "application","data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <%= render 'layouts/shim' %>
<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css">
<script src="http://code.jquery.com/jquery-1.10.2.js"></script>
<script src="http://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
<link rel="stylesheet" href="/resources/demos/style.css">

<script>
$(function() {
$( "#datepicker" ).datepicker({dateFormat: 'yy/mm/dd'});
$( "#datepicker1" ).datepicker({dateFormat: 'yy/mm/dd'});
$( "#datepicker2" ).datepicker({dateFormat: 'yy/mm/dd'});

});
</script>
</head>

<body>
    <%= render 'layouts/header' %>
    <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <div class="container">
      <%= yield %>
    </div>
</body>

</html>